global:
  resolve_timeout: 5m

templates:
  - "/etc/alertmanager/discord.tmpl"

route:
  receiver: discord
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: discord
    webhook_configs:
      - url: "http://discord-proxy:5000"
        send_resolved: true